# Generated by Django 2.2.4 on 2019-11-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20191122_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
