# Generated by Django 2.2.4 on 2019-11-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20191122_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
