# Generated by Django 2.2.4 on 2019-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20191122_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.CharField(default='03F38D7', max_length=10, unique=True),
        ),
    ]
