# Generated by Django 2.2.4 on 2019-11-22 19:27

from django.db import migrations, models
import entry.generateuiniquetoken


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20191122_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.CharField(default=entry.generateuiniquetoken.generate, max_length=10, unique=True),
        ),
    ]
