# Generated by Django 2.2.4 on 2019-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_auto_20191122_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
