# Generated by Django 2.2.4 on 2019-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20191122_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_out',
            field=models.TimeField(blank=True),
        ),
    ]
